### ISSUE TITLE
GCP Instructions

### ISSUE THREAD

**Issue by erickufrin** [mrdanielmh/asa-session-replay#1]
I was able to get this working (yay!) using this guide, however I took a long detour troubleshooting the final part of converting the session and uploading to GCP. I troubleshot all sorts of stuff except the line inotifywait .... Turns out I was missing inotify-tools. Looking at the readme I can now see that install was only mentioned for AWS.

For GCP mention this: **apt install inotify-tools**

Also might be worth mentioning that the (Bucket Access IAM Service Acct) GCP service account key should include everything within quotes for private_key. Including the -----BEGIN PRIVATE KEY-----\n **_and_** \n-----END PRIVATE KEY-----\n sections. I assumed this should be trimmed and the error message was not exactly telling exactly what was wrong there.

And that the GCP instance hosting the gateway should be using the same (Bucket Access IAM Service Acct) should be used as the instance service account.

Great work putting this together!

**Comment by mrdanielmh** [comment]
Thanks Eric! I've updated the notes to include your comments
